### ISSUE TITLE
Missing published date

### ISSUE THREAD

**Issue by hoanhan101** [nayeemaquib/nayeemaquib.github.io#1]
I was looking at your blog post at [http://www.nayeemaquib.com/texts/2018-03-12-how-to-use-multiple-github-accounts-from-the-same-machine/](http://www.nayeemaquib.com/texts/2018-03-12-how-to-use-multiple-github-accounts-from-the-same-machine/) and couldn't find the published date. However, from the URL, I can probably tell that it was uploaded on March 12th, 2018. It would be great if you can also include that inside. One suggestion would be under the title of the post.

Great post by the way!

**Comment by nayeemaquib** [comment]
Thanks! Great suggestion. You will find the dates under the title from now on.

**Comment by hoanhan101** [comment]
LGTM!
